id: A42111E94
base_file: f734A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:12:29.188788
  last_modified_at: 2022-05-30 23:12:29.188835
