id: A42111E94
base_file: f3AA3.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:12:29.181002
  last_modified_at: 2022-05-30 23:12:29.181006
