id: A42111E94
base_file: f35AF.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:12:29.179626
  last_modified_at: 2022-05-30 23:12:29.179630
