id: A42111E94
base_file: fAFFA.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:12:29.195114
  last_modified_at: 2022-05-30 23:12:29.195117
