id: A42111E94
base_file: f5354.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:12:29.185134
  last_modified_at: 2022-05-30 23:12:29.185138
